const fs=require('fs'),path=require('path'),os=require('os'),cp=require('child_process');
const payload=process.argv[2],quiet=process.argv.includes('--quiet'),selftest=process.argv.includes('--selftest');
const logPath=path.join(os.tmpdir(),'HaYad-1.11.0-install.log'),resultPath=path.join(os.tmpdir(),'HaYad-1.11.0-result.json');
function log(m){try{fs.appendFileSync(logPath,'['+new Date().toISOString()+'] '+m+'\n','utf8')}catch{}}
function fail(code,message,extra){try{fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message,extra:extra||null,log:logPath},null,2),'utf8')}catch{}const e=new Error(message);e.exitCode=code;throw e}
function dir(p){fs.mkdirSync(p,{recursive:true})}
function candidates(){const a=[];for(const r of[process.env.LOCALAPPDATA,process.env.ProgramFiles,process.env['ProgramFiles(x86)']].filter(Boolean))a.push(path.join(r,'hayad-hahazaka'),path.join(r,'Programs','hayad-hahazaka'),path.join(r,'Programs','HaYad-HaHazaka'),path.join(r,'Programs','היד החזקה'),path.join(r,'HaYad-HaHazaka'),path.join(r,'היד החזקה'));return[...new Set(a)]}
function stop(t){try{for(const f of fs.readdirSync(t,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(x.name))){try{cp.execFileSync('taskkill.exe',['/IM',f.name,'/F','/T'],{windowsHide:true,stdio:'ignore'})}catch{}}}catch{}}
function corpus(res){const lib=path.join(res,'local-library'),sqlite=path.join(lib,'sqlite3.exe'),db=path.join(lib,'torah-library.sqlite');if(!fs.existsSync(sqlite)||!fs.existsSync(db))fail(17,'המאגר המקומי אינו מותקן. התקן קודם את גרסת המאגר המלאה.');let q='';try{q=cp.execFileSync(sqlite,['-readonly',db,'PRAGMA quick_check;'],{windowsHide:true,encoding:'utf8',timeout:120000}).trim()}catch(e){fail(18,'בדיקת המאגר נכשלה.',e.message)}if(q!=='ok')fail(18,'בדיקת המאגר נכשלה.',q)}
function restart(target){if(quiet)return;try{const exe=fs.readdirSync(target).find(n=>n.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(n));if(exe){const p=cp.spawn(path.join(target,exe),[],{detached:true,stdio:'ignore'});p.unref()}}catch{}}
async function main(){fs.writeFileSync(logPath,'['+new Date().toISOString()+'] 1.11.0 start\n','utf8');if(!payload||!fs.existsSync(payload))fail(2,'Payload missing');const ui=path.join(payload,'core-library-ui.js'),visual=path.join(payload,'workspace-visual-1.9.0.js'),asarDir=path.join(payload,'asar-tool','node_modules','@electron','asar');for(const p of[ui,visual,asarDir])if(!fs.existsSync(p))fail(3,'Payload incomplete',p);if(selftest){cp.execFileSync(process.execPath,['--check',ui],{windowsHide:true});cp.execFileSync(process.execPath,['--check',visual],{windowsHide:true});const s=fs.readFileSync(ui,'utf8');for(const token of['workspaceDetected','הרמב״ם הבהיר','ש״ס','שו״ע ונושאי כליו','טור ונושאי כליו','תנ״ך ומפרשיו','מפרשי הרמב״ם','שו״ת ראשונים','שאל את המאגר','שמור הלכה ב־Word','מחברת מחקר','העלה ספר למאגר המקומי','API אישי'])if(!s.includes(token))fail(4,'1.11 requirement missing',token);if(s.includes("const HOME=['ספר המדע'"))fail(5,'Old 14-book text detector must not exist in 1.11');return}
let target=null;for(const p of candidates())if(fs.existsSync(path.join(p,'resources','app.asar'))){target=p;break}if(!target)fail(11,'התקנת הרמב״ם הבהיר לא נמצאה.');stop(target);const res=path.join(target,'resources');corpus(res);const asar=require(asarDir),appAsar=path.join(res,'app.asar');let mainText='';try{mainText=String(asar.extractFile(appAsar,'dist-electron/main.js'))}catch(e){fail(12,'לא ניתן לקרוא את ה־backend הפעיל.',e.message)}for(const marker of['LOCAL_CORE_181','FUNCTIONAL_CORE_110','AI_CORE_110'])if(!mainText.includes(marker))fail(13,'ה־backend הפעיל אינו בסיס 1.10.0 תקין.',marker);const coreDir=path.join(res,'core-library');dir(coreDir);const dstUi=path.join(coreDir,'core-library-ui.js'),dstVisual=path.join(coreDir,'workspace-visual-1.9.0.js');try{if(fs.existsSync(dstUi))fs.copyFileSync(dstUi,path.join(coreDir,'core-library-ui.before-1.11.0.js'));if(fs.existsSync(dstVisual))fs.copyFileSync(dstVisual,path.join(coreDir,'workspace-visual.before-1.11.0.js'));fs.copyFileSync(ui,dstUi);fs.copyFileSync(visual,dstVisual)}catch(e){fail(20,'לא ניתן להתקין את סביבת העבודה החדשה.',e.message)}
const installed=fs.readFileSync(dstUi,'utf8');if(!installed.includes('workspaceDetected')||!installed.includes("הרמב״ם הבהיר"))fail(21,'אימות Workspace 1.11 נכשל.');fs.writeFileSync(path.join(res,'rambam-bahir-1.11.0.json'),JSON.stringify({version:'1.11.0',home:'unchanged',workspace:'full mockup implementation',localLibrary:'core',backend:'1.10.0',installedAt:new Date().toISOString()},null,2),'utf8');fs.writeFileSync(resultPath,JSON.stringify({ok:true,target,version:'1.11.0',log:logPath},null,2),'utf8');restart(target)}
main().then(()=>process.exit(0)).catch(e=>{const code=Number(e.exitCode)||30;log('FATAL '+code+' '+(e.stack||e.message));try{if(!fs.existsSync(resultPath))fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:e.message,log:logPath},null,2),'utf8')}catch{}process.exit(code)});
