const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),cp=require('child_process');
const payload=process.argv[2],quiet=process.argv.includes('--quiet'),selftest=process.argv.includes('--selftest');
const logPath=path.join(os.tmpdir(),'HaYad-1.8.1-install.log'),resultPath=path.join(os.tmpdir(),'HaYad-1.8.1-result.json');
function log(m){try{fs.appendFileSync(logPath,`[${new Date().toISOString()}] ${m}\n`,'utf8')}catch{}}
function fail(code,msg,extra){const d={ok:false,code,message:msg,extra:extra||null,log:logPath};log(`ERROR ${code}: ${msg}${extra?` / ${extra}`:''}`);try{fs.writeFileSync(resultPath,JSON.stringify(d,null,2),'utf8')}catch{}const e=new Error(msg);e.exitCode=code;throw e}
function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}
function ensureDir(p){fs.mkdirSync(p,{recursive:true})}function rm(p){try{fs.rmSync(p,{recursive:true,force:true})}catch{}}
function candidates(){const o=[];for(const r of [process.env.LOCALAPPDATA,process.env.ProgramFiles,process.env['ProgramFiles(x86)']].filter(Boolean))o.push(path.join(r,'hayad-hahazaka'),path.join(r,'Programs','hayad-hahazaka'),path.join(r,'Programs','HaYad-HaHazaka'),path.join(r,'Programs','היד החזקה'),path.join(r,'HaYad-HaHazaka'),path.join(r,'היד החזקה'));return[...new Set(o)]}
function validateRenderer(d){const e={[path.join('dist','assets','index.js')]:'e2a301bad496d87490eaceb091204d2287fa60f00c5d22341403e6f8daa69e76',[path.join('dist','assets','index.css')]:'6df2817f475b85236d7c4764d1fa2339673b3d827cd6442fbce042b5dbcefc37',[path.join('dist','index.html')]:'74e52686fc6f255043062277f385b45cd85e2fdd16abc42dc00afbe18913de24'};for(const [r,w] of Object.entries(e)){const p=path.join(d,r);if(!fs.existsSync(p)||sha(p)!==w)return false}return true}
function inspectMain(d){const p=path.join(d,'dist-electron','main.js');if(!fs.existsSync(p))return{kind:'unknown',main:p,text:''};const t=fs.readFileSync(p,'utf8');if(t.includes('LOCAL_CORE_180'))return{kind:'core',main:p,text:t};if(t.includes('LOCAL_CORPUS_176'))return{kind:'176',main:p,text:t};if(t.includes("_electron.ipcMain.handle('knowledge:list', () => store.read().knowledge)")&&t.includes('function ensureMaster() {'))return{kind:'163',main:p,text:t};return{kind:'unknown',main:p,text:t}}
function stopApp(t){try{for(const f of fs.readdirSync(t,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(x.name))){try{cp.execFileSync('taskkill.exe',['/IM',f.name,'/F','/T'],{windowsHide:true,stdio:'ignore'})}catch{}}}catch{}}
function inspectCorpus(res){const lib=path.join(res,'local-library'),sqlite=path.join(lib,'sqlite3.exe'),db=path.join(lib,'torah-library.sqlite');if(!fs.existsSync(sqlite)||!fs.existsSync(db))fail(17,'המאגר המקומי אינו מותקן. יש להתקין תחילה את גרסה 1.7.5 המלאה.');let q='';try{q=cp.execFileSync(sqlite,['-readonly',db,'PRAGMA quick_check;'],{windowsHide:true,encoding:'utf8',timeout:120000}).trim()}catch(e){fail(18,'לא ניתן לבדוק את המאגר המקומי.',e.message)}if(q!=='ok')fail(18,'בדיקת תקינות המאגר נכשלה.',q);let s={books:0,segments:0};try{const raw=cp.execFileSync(sqlite,['-readonly','-json',db,"SELECT (SELECT count(*) FROM books) AS books,(SELECT count(*) FROM segments) AS segments;"],{windowsHide:true,encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024}).trim();s=(raw?JSON.parse(raw):[])[0]||s}catch(e){fail(18,'לא ניתן לקרוא את נתוני המאגר.',e.message)}if(+s.books<100||+s.segments<10000)fail(18,'המאגר המקומי קטן או פגום.',JSON.stringify(s));return{db,books:+s.books,segments:+s.segments}}
function runPatch(node,script,main,pkg,code,label){try{const out=cp.execFileSync(node,[script,main,pkg],{windowsHide:true,encoding:'utf8',maxBuffer:32*1024*1024});log(`${label} OK: ${String(out||'').trim()}`)}catch(e){const extra=[e.message,e.stdout&&String(e.stdout),e.stderr&&String(e.stderr)].filter(Boolean).join('\n').slice(0,4000);fail(code,`${label} נכשל.`,extra)}}
async function main(){fs.writeFileSync(logPath,`[${new Date().toISOString()}] Starting HaYad 1.8.1 robust Core Library installer\n`,'utf8');if(!payload||!fs.existsSync(payload))fail(2,'Payload folder missing',payload||'');const asarDir=path.join(payload,'asar-tool','node_modules','@electron','asar'),p176=path.join(payload,'patch-main-1.7.6.js'),p180=path.join(payload,'patch-core-1.8.0.js');for(const p of[asarDir,p176,p180])if(!fs.existsSync(p))fail(3,'Installer payload incomplete',p);const asar=require(asarDir),node=process.execPath;
if(selftest){const fixture=path.join(os.tmpdir(),'HaYad181Fixture');rm(fixture);ensureDir(path.join(fixture,'dist-electron'));ensureDir(path.join(fixture,'dist','assets'));fs.writeFileSync(path.join(fixture,'dist','assets','index.js'),'fixture');fs.writeFileSync(path.join(fixture,'dist','assets','index.css'),'fixture');fs.writeFileSync(path.join(fixture,'dist','index.html'),'fixture');const t180=fs.readFileSync(p180,'utf8');if(!t180.includes('LOCAL_CORE_180')||!t180.includes('rb-core-bar'))fail(4,'Core patch assertions missing');const t176=fs.readFileSync(p176,'utf8');if(!t176.includes("process.resourcesPath, 'local-library'"))fail(5,'1.7.6 path assertions missing');log('SELFTEST OK: robust upgrade-path assertions');return}
let target=null;for(const p of candidates())if(fs.existsSync(path.join(p,'resources','app.asar'))){target=p;break}if(!target)fail(11,'לא נמצאה התקנת היד החזקה קיימת.');stopApp(target);const res=path.join(target,'resources'),corpus=inspectCorpus(res),current=path.join(res,'app.asar'),backup=path.join(res,'app-1.6.3-original.asar'),workRoot=path.join(os.tmpdir(),'HaYad181Work');rm(workRoot);ensureDir(workRoot);
let source=null,kind=null;for(const candidate of [current,backup].filter((v,i,a)=>a.indexOf(v)===i&&fs.existsSync(v))){const d=path.join(workRoot,'inspect-'+crypto.randomBytes(3).toString('hex'));ensureDir(d);try{await Promise.resolve(asar.extractAll(candidate,d));if(!validateRenderer(d)){log('Renderer mismatch in '+candidate);continue}const info=inspectMain(d);log(`Candidate ${candidate} kind=${info.kind}`);if(info.kind==='176'||info.kind==='163'||info.kind==='core'){source=candidate;kind=info.kind;break}}catch(e){log('Candidate inspect failed: '+e.message)}finally{rm(d)}}if(!source)fail(12,'לא נמצאה חבילת בסיס תקינה עם ממשק 1.6.3 המאושר. לא בוצע שינוי.');
if(kind==='core'){const d=path.join(workRoot,'already');ensureDir(d);await Promise.resolve(asar.extractAll(source,d));const pkg=path.join(d,'package.json');try{const j=JSON.parse(fs.readFileSync(pkg,'utf8'));j.version='1.8.1';fs.writeFileSync(pkg,JSON.stringify(j,null,2),'utf8')}catch{}const outAsar=path.join(workRoot,'app-1.8.1.asar');await asar.createPackage(d,outAsar);fs.copyFileSync(outAsar,current);log('Core Library already present; version metadata refreshed');}
else{const work=path.join(workRoot,'app');ensureDir(work);await Promise.resolve(asar.extractAll(source,work));if(!validateRenderer(work))fail(13,'נעילת העיצוב נכשלה לפני העדכון.');const mainPath=path.join(work,'dist-electron','main.js'),pkgPath=path.join(work,'package.json');if(kind==='163')runPatch(node,p176,mainPath,pkgPath,22,'הכנת backend 1.7.6');runPatch(node,p180,mainPath,pkgPath,23,'הטמעת Core Library');if(!validateRenderer(work))fail(14,'קבצי ה-UI של 1.6.3 השתנו. העדכון בוטל.');const mt=fs.readFileSync(mainPath,'utf8');if(!mt.includes('LOCAL_CORE_180'))fail(15,'שכבת Core Library לא נוספה.');try{const j=JSON.parse(fs.readFileSync(pkgPath,'utf8'));j.version='1.8.1';fs.writeFileSync(pkgPath,JSON.stringify(j,null,2),'utf8')}catch(e){fail(24,'עדכון מספר הגרסה נכשל.',e.message)}const outAsar=path.join(workRoot,'app-1.8.1.asar');try{await asar.createPackage(work,outAsar)}catch(e){fail(25,'אריזת app.asar נכשלה.',e.message)}const verify=path.join(workRoot,'verify');ensureDir(verify);try{await Promise.resolve(asar.extractAll(outAsar,verify))}catch(e){fail(26,'בדיקת app.asar נכשלה.',e.message)}if(!validateRenderer(verify))fail(16,'בדיקת ASAR סופית נכשלה: ממשק 1.6.3 אינו זהה.');try{fs.copyFileSync(outAsar,current)}catch(e){fail(19,'החלפת app.asar נכשלה.',e.message)}}
const final=path.join(workRoot,'final');ensureDir(final);try{await Promise.resolve(asar.extractAll(current,final))}catch(e){fail(27,'לא ניתן לפתוח את החבילה לאחר ההתקנה.',e.message)}if(!validateRenderer(final))fail(20,'בדיקת העיצוב לאחר ההתקנה נכשלה.');if(!fs.readFileSync(path.join(final,'dist-electron','main.js'),'utf8').includes('LOCAL_CORE_180'))fail(21,'בדיקת Core Library לאחר ההתקנה נכשלה.');const meta={version:'1.8.1',base:'1.6.3',coreLibrary:true,books:corpus.books,segments:corpus.segments,sourceKind:kind,installedAt:new Date().toISOString()};fs.writeFileSync(path.join(res,'rambam-bahir-1.8.1.json'),JSON.stringify(meta,null,2),'utf8');rm(workRoot);fs.writeFileSync(resultPath,JSON.stringify({ok:true,target,...meta,log:logPath},null,2),'utf8');log('SUCCESS 1.8.1');if(!quiet){try{const exe=fs.readdirSync(target).find(n=>n.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(n));if(exe){const p=cp.spawn(path.join(target,exe),[],{detached:true,stdio:'ignore'});p.unref()}}catch(e){log('Launch skipped: '+e.message)}}}
main().then(()=>process.exit(0)).catch(err=>{const code=Number(err.exitCode)||30;const extra=err.stack||err.message;log(`FATAL ${code}: ${extra}`);try{if(!fs.existsSync(resultPath))fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:err.message,stack:extra,log:logPath},null,2),'utf8')}catch{}process.exit(code)});
