const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),cp=require('child_process');
const payload=process.argv[2],quiet=process.argv.includes('--quiet'),selftest=process.argv.includes('--selftest');
const logPath=path.join(os.tmpdir(),'HaYad-1.8.3-install.log'),resultPath=path.join(os.tmpdir(),'HaYad-1.8.3-result.json');
function log(m){try{fs.appendFileSync(logPath,'['+new Date().toISOString()+'] '+m+'\n','utf8')}catch{}}
function fail(code,msg,extra){const d={ok:false,code,message:msg,extra:extra||null,log:logPath};log('ERROR '+code+': '+msg+(extra?' / '+extra:''));try{fs.writeFileSync(resultPath,JSON.stringify(d,null,2),'utf8')}catch{}const e=new Error(msg);e.exitCode=code;throw e}
function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}
function dir(p){fs.mkdirSync(p,{recursive:true})}function rm(p){try{fs.rmSync(p,{recursive:true,force:true})}catch{}}
const UI_HASHES={
  [path.join('dist','assets','index.js')]:'e2a301bad496d87490eaceb091204d2287fa60f00c5d22341403e6f8daa69e76',
  [path.join('dist','assets','index.css')]:'6df2817f475b85236d7c4764d1fa2339673b3d827cd6442fbce042b5dbcefc37',
  [path.join('dist','index.html')]:'74e52686fc6f255043062277f385b45cd85e2fdd16abc42dc00afbe18913de24'
};
function rendererReport(d){const bad=[];for(const [r,w] of Object.entries(UI_HASHES)){const p=path.join(d,r);const actual=fs.existsSync(p)?sha(p):'MISSING';if(actual!==w)bad.push({file:r,expected:w,actual})}return bad}
function rendererOk(d){const bad=rendererReport(d);if(bad.length)log('UI mismatch '+JSON.stringify(bad));return bad.length===0}
function candidates(){const a=[];for(const r of [process.env.LOCALAPPDATA,process.env.ProgramFiles,process.env['ProgramFiles(x86)']].filter(Boolean))a.push(path.join(r,'hayad-hahazaka'),path.join(r,'Programs','hayad-hahazaka'),path.join(r,'Programs','HaYad-HaHazaka'),path.join(r,'Programs','היד החזקה'),path.join(r,'HaYad-HaHazaka'),path.join(r,'היד החזקה'));return[...new Set(a)]}
function kindOf(d){const p=path.join(d,'dist-electron','main.js');if(!fs.existsSync(p))return'unknown';const t=fs.readFileSync(p,'utf8');if(t.includes('LOCAL_CORE_181'))return'181';if(t.includes('LOCAL_CORE_180'))return'180';if(t.includes('LOCAL_CORPUS_176'))return'176';if(t.includes("_electron.ipcMain.handle('knowledge:list', () => store.read().knowledge)")&&t.includes('function ensureMaster() {'))return'163';return'unknown'}
function stopApp(t){try{for(const f of fs.readdirSync(t,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(x.name))){try{cp.execFileSync('taskkill.exe',['/IM',f.name,'/F','/T'],{windowsHide:true,stdio:'ignore'})}catch{}}}catch{}}
function corpus(res){const lib=path.join(res,'local-library'),sqlite=path.join(lib,'sqlite3.exe'),db=path.join(lib,'torah-library.sqlite');if(!fs.existsSync(sqlite)||!fs.existsSync(db))fail(17,'Local corpus is not installed. Install the full 1.7.5 corpus package first.');let q='';try{q=cp.execFileSync(sqlite,['-readonly',db,'PRAGMA quick_check;'],{windowsHide:true,encoding:'utf8',timeout:120000}).trim()}catch(e){fail(18,'Local corpus integrity check failed.',e.message)}if(q!=='ok')fail(18,'Local corpus integrity check failed.',q);let s={books:0,segments:0};try{const raw=cp.execFileSync(sqlite,['-readonly','-json',db,"SELECT (SELECT count(*) FROM books) AS books,(SELECT count(*) FROM segments) AS segments;"],{windowsHide:true,encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024}).trim();s=(raw?JSON.parse(raw):[])[0]||s}catch(e){fail(18,'Cannot read local corpus statistics.',e.message)}if(+s.books<100||+s.segments<10000)fail(18,'Local corpus is incomplete.',JSON.stringify(s));return{books:+s.books,segments:+s.segments}}
function run(node,script,main,pkg,code,label){try{const out=cp.execFileSync(node,[script,main,pkg],{windowsHide:true,encoding:'utf8',maxBuffer:32*1024*1024});log(label+' OK '+String(out||'').trim())}catch(e){fail(code,label+' failed.',[e.message,e.stdout&&String(e.stdout),e.stderr&&String(e.stderr)].filter(Boolean).join('\n').slice(0,6000))}}
async function extract(asar,file,to){dir(to);await Promise.resolve(asar.extractAll(file,to))}
function rollback(liveDir,oldLive){rm(liveDir);if(fs.existsSync(oldLive)){try{fs.renameSync(oldLive,liveDir);log('Rollback restored previous resources/app')}catch(e){log('Rollback restore failed '+e.message)}}}
async function main(){fs.writeFileSync(logPath,'['+new Date().toISOString()+'] Starting HaYad 1.8.3 direct-extract repair\n','utf8');if(!payload||!fs.existsSync(payload))fail(2,'Payload folder missing',payload||'');
const asarDir=path.join(payload,'asar-tool','node_modules','@electron','asar'),p176=path.join(payload,'patch-main-1.7.6.cjs'),p181=path.join(payload,'patch-core-1.8.1.cjs'),ui=path.join(payload,'core-library-ui.js');for(const p of[asarDir,p176,p181,ui])if(!fs.existsSync(p))fail(3,'Installer payload incomplete',p);const asar=require(asarDir),node=process.execPath;
if(selftest){const a=fs.readFileSync(p181,'utf8'),u=fs.readFileSync(ui,'utf8');if(!a.includes('LOCAL_CORE_181')||!a.includes('core-library-ui.js'))fail(4,'Core backend assertions missing');if(!u.includes('rb-core-bar')||!u.includes('ספריית הספרים')||!u.includes('שאל במאגר'))fail(5,'Core UI assertions missing');log('SELFTEST OK');return}
let target=null;for(const p of candidates())if(fs.existsSync(path.join(p,'resources','app.asar'))){target=p;break}if(!target)fail(11,'Existing HaYad installation was not found.');stopApp(target);
const res=path.join(target,'resources'),c=corpus(res),current=path.join(res,'app.asar'),original=path.join(res,'app-1.6.3-original.asar'),pre=path.join(res,'app-before-1.8.3.asar'),liveDir=path.join(res,'app'),oldLive=path.join(res,'app-before-1.8.3-dir'),workRoot=path.join(os.tmpdir(),'HaYad183Work');rm(workRoot);dir(workRoot);try{fs.copyFileSync(current,pre)}catch(e){fail(30,'Cannot create app.asar safety backup.',e.message)}
let source=null,kind='unknown';for(const candidate of [original,current,pre].filter((v,i,a)=>a.indexOf(v)===i&&fs.existsSync(v))){const d=path.join(workRoot,'inspect-'+crypto.randomBytes(3).toString('hex'));try{await extract(asar,candidate,d);const bad=rendererReport(d);if(bad.length){log('Skipped '+candidate+' '+JSON.stringify(bad));continue}const k=kindOf(d);log('Candidate '+candidate+' kind='+k);if(['163','176','181'].includes(k)){source=candidate;kind=k;break}if(k==='180')log('Skipping legacy 1.8.0 backend')}catch(e){log('Candidate inspect failed '+candidate+': '+e.message)}finally{rm(d)}}
if(!source)fail(12,'No verified 1.6.3-renderer base package was found. No changes were made.');
rm(oldLive);if(fs.existsSync(liveDir)){try{fs.renameSync(liveDir,oldLive)}catch(e){fail(33,'Cannot back up existing resources/app.',e.message)}}
try{await extract(asar,source,liveDir)}catch(e){rollback(liveDir,oldLive);fail(34,'Direct extraction to resources/app failed.',e.message)}
let bad=rendererReport(liveDir);if(bad.length){rollback(liveDir,oldLive);fail(20,'UI hash verification failed immediately after direct ASAR extraction.',JSON.stringify(bad))}
const mainPath=path.join(liveDir,'dist-electron','main.js'),pkgPath=path.join(liveDir,'package.json');try{if(kind==='163')run(node,p176,mainPath,pkgPath,22,'Prepare 1.7.6 backend');if(kind!=='181')run(node,p181,mainPath,pkgPath,23,'Install Core Library backend 1.8.1')}catch(e){rollback(liveDir,oldLive);throw e}
bad=rendererReport(liveDir);if(bad.length){rollback(liveDir,oldLive);fail(14,'UI files changed during backend patch; rolled back.',JSON.stringify(bad))}if(kindOf(liveDir)!=='181'){rollback(liveDir,oldLive);fail(21,'Core backend verification failed; rolled back.',kindOf(liveDir))}
try{const j=JSON.parse(fs.readFileSync(pkgPath,'utf8'));j.version='1.8.3';fs.writeFileSync(pkgPath,JSON.stringify(j,null,2),'utf8')}catch(e){rollback(liveDir,oldLive);fail(24,'Version metadata update failed; rolled back.',e.message)}
const uiDir=path.join(res,'core-library'),uiFinal=path.join(uiDir,'core-library-ui.js');try{dir(uiDir);fs.copyFileSync(ui,uiFinal)}catch(e){rollback(liveDir,oldLive);fail(31,'Core Library UI installation failed; rolled back.',e.message)}if(!fs.existsSync(uiFinal)||!fs.readFileSync(uiFinal,'utf8').includes('rb-core-bar')){rollback(liveDir,oldLive);fail(32,'Core Library UI verification failed; rolled back.')}
const finalBad=rendererReport(liveDir);if(finalBad.length){rollback(liveDir,oldLive);fail(25,'Final UI verification failed; rolled back.',JSON.stringify(finalBad))}
const meta={version:'1.8.3',base:'1.6.3',renderer:'byte-identical',deployment:'direct ASAR extract to resources/app',coreLibrary:true,books:c.books,segments:c.segments,sourceKind:kind,uiFile:uiFinal,installedAt:new Date().toISOString()};fs.writeFileSync(path.join(res,'rambam-bahir-1.8.3.json'),JSON.stringify(meta,null,2),'utf8');rm(workRoot);fs.writeFileSync(resultPath,JSON.stringify({ok:true,target,...meta,log:logPath},null,2),'utf8');log('SUCCESS 1.8.3');if(!quiet){try{const exe=fs.readdirSync(target).find(n=>n.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(n));if(exe){const p=cp.spawn(path.join(target,exe),[],{detached:true,stdio:'ignore'});p.unref()}}catch(e){log('Launch skipped '+e.message)}}}
main().then(()=>process.exit(0)).catch(err=>{const code=Number(err.exitCode)||30;const extra=err.stack||err.message;log('FATAL '+code+': '+extra);try{if(!fs.existsSync(resultPath))fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:err.message,stack:extra,log:logPath},null,2),'utf8')}catch{}process.exit(code)});
