const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),cp=require('child_process');
const payload=process.argv[2],quiet=process.argv.includes('--quiet'),selftest=process.argv.includes('--selftest');
const logPath=path.join(os.tmpdir(),'HaYad-1.10.0-install.log'),resultPath=path.join(os.tmpdir(),'HaYad-1.10.0-result.json');
function log(m){try{fs.appendFileSync(logPath,'['+new Date().toISOString()+'] '+m+'\n','utf8')}catch{}}function fail(code,msg,extra){try{fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:msg,extra:extra||null,log:logPath},null,2),'utf8')}catch{}const e=new Error(msg);e.exitCode=code;throw e}function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}function dir(p){fs.mkdirSync(p,{recursive:true})}function rm(p){try{fs.rmSync(p,{recursive:true,force:true})}catch{}}
const UI={[path.join('dist','assets','index.js')]:'e2a301bad496d87490eaceb091204d2287fa60f00c5d22341403e6f8daa69e76',[path.join('dist','assets','index.css')]:'6df2817f475b85236d7c4764d1fa2339673b3d827cd6442fbce042b5dbcefc37',[path.join('dist','index.html')]:'74e52686fc6f255043062277f385b45cd85e2fdd16abc42dc00afbe18913de24'};
function report(d){const a=[];for(const[r,w]of Object.entries(UI)){const p=path.join(d,r),x=fs.existsSync(p)?sha(p):'MISSING';if(x!==w)a.push({file:r,expected:w,actual:x})}return a}function ok(d){return report(d).length===0}
function candidates(){const a=[];for(const r of[process.env.LOCALAPPDATA,process.env.ProgramFiles,process.env['ProgramFiles(x86)']].filter(Boolean))a.push(path.join(r,'hayad-hahazaka'),path.join(r,'Programs','hayad-hahazaka'),path.join(r,'Programs','HaYad-HaHazaka'),path.join(r,'Programs','היד החזקה'),path.join(r,'HaYad-HaHazaka'),path.join(r,'היד החזקה'));return[...new Set(a)]}
function mainText(d){const p=path.join(d,'dist-electron','main.js');return fs.existsSync(p)?fs.readFileSync(p,'utf8'):''}function kind(d){const t=mainText(d);if(t.includes('FUNCTIONAL_CORE_110'))return'110';if(t.includes('WORKSPACE_VISUAL_190'))return'190';if(t.includes('LOCAL_CORE_181'))return'181';if(t.includes('LOCAL_CORPUS_176'))return'176';if(t.includes("_electron.ipcMain.handle('knowledge:list', () => store.read().knowledge)")&&t.includes('function ensureMaster() {'))return'163';return'unknown'}function hasAi(d){return mainText(d).includes('AI_CORE_110')}
function stop(t){try{for(const f of fs.readdirSync(t,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(x.name))){try{cp.execFileSync('taskkill.exe',['/IM',f.name,'/F','/T'],{windowsHide:true,stdio:'ignore'})}catch{}}}catch{}}
function corpus(res){const lib=path.join(res,'local-library'),sqlite=path.join(lib,'sqlite3.exe'),db=path.join(lib,'torah-library.sqlite');if(!fs.existsSync(sqlite)||!fs.existsSync(db))fail(17,'המאגר המקומי אינו מותקן.');let q='';try{q=cp.execFileSync(sqlite,['-readonly',db,'PRAGMA quick_check;'],{windowsHide:true,encoding:'utf8',timeout:120000}).trim()}catch(e){fail(18,'בדיקת המאגר נכשלה.',e.message)}if(q!=='ok')fail(18,'בדיקת המאגר נכשלה.',q)}
function run(node,script,main,pkg,code,label){try{cp.execFileSync(node,[script,main,pkg],{windowsHide:true,encoding:'utf8',maxBuffer:32*1024*1024})}catch(e){fail(code,label,[e.message,e.stdout&&String(e.stdout),e.stderr&&String(e.stderr)].filter(Boolean).join('\n').slice(0,6000))}}async function extract(asar,file,to){dir(to);await Promise.resolve(asar.extractAll(file,to))}
async function main(){fs.writeFileSync(logPath,'['+new Date().toISOString()+'] 1.10.0 start\n','utf8');if(!payload||!fs.existsSync(payload))fail(2,'Payload missing');const asarDir=path.join(payload,'asar-tool','node_modules','@electron','asar'),p176=path.join(payload,'patch-main-1.7.6.cjs'),p181=path.join(payload,'patch-core-1.8.1.cjs'),p190=path.join(payload,'patch-visual-1.9.0.cjs'),p110=path.join(payload,'patch-functional-1.10.0.cjs'),pAi=path.join(payload,'patch-api-1.10.0.cjs'),coreUi=path.join(payload,'core-library-ui.js'),visual=path.join(payload,'workspace-visual-1.9.0.js');for(const p of[asarDir,p176,p181,p190,p110,pAi,coreUi,visual])if(!fs.existsSync(p))fail(3,'Payload incomplete',p);const asar=require(asarDir),node=process.execPath;if(selftest){for(const p of[p176,p181,p190,p110,pAi,coreUi,visual])cp.execFileSync(node,['--check',p],{windowsHide:true});const c=fs.readFileSync(coreUi,'utf8');if(!c.includes('ש״ס')||!c.includes('מחברת מחקר')||!c.includes('שמור הלכה ב־Word')||!c.includes('הגדר API')||!c.includes('שאל את המאגר'))fail(4,'1.10 functional assertions missing');return}
let target=null;for(const p of candidates())if(fs.existsSync(path.join(p,'resources','app.asar'))){target=p;break}if(!target)fail(11,'התקנת הרמב״ם הבהיר לא נמצאה.');stop(target);const res=path.join(target,'resources');corpus(res);const current=path.join(res,'app.asar'),original=path.join(res,'app-1.6.3-original.asar'),backup=path.join(res,'app-before-1.10.0.asar'),workRoot=path.join(os.tmpdir(),'HaYad110Work');rm(workRoot);dir(workRoot);try{fs.copyFileSync(current,backup)}catch(e){fail(30,'לא ניתן ליצור גיבוי.',e.message)}
const sourceCandidates=[original,current,path.join(res,'app-before-1.9.1.asar')].filter((v,i,a)=>a.indexOf(v)===i&&fs.existsSync(v));let source=null;for(const f of sourceCandidates){const d=path.join(workRoot,'i'+crypto.randomBytes(3).toString('hex'));try{await extract(asar,f,d);if(ok(d)&&['163','176','181','190','110'].includes(kind(d))){source=f;break}}catch(e){log(e.message)}finally{rm(d)}}if(!source)fail(12,'לא נמצא בסיס מאומת של 1.6.3.');const work=path.join(workRoot,'app');await extract(asar,source,work);if(!ok(work))fail(20,'בדיקת ממשק נכשלה.',JSON.stringify(report(work)));const mainPath=path.join(work,'dist-electron','main.js'),pkgPath=path.join(work,'package.json');let k=kind(work);if(k==='163'){run(node,p176,mainPath,pkgPath,22,'1.7.6 patch failed');k=kind(work)}if(k==='176'){run(node,p181,mainPath,pkgPath,23,'1.8.1 patch failed');k=kind(work)}if(k==='181'){run(node,p190,mainPath,pkgPath,24,'1.9 patch failed');k=kind(work)}if(k==='190'){run(node,p110,mainPath,pkgPath,25,'1.10 patch failed');k=kind(work)}if(k!=='110')fail(26,'1.10 backend verification failed',k);if(!hasAi(work))run(node,pAi,mainPath,pkgPath,31,'API patch failed');if(!hasAi(work))fail(32,'API backend verification failed');if(!ok(work))fail(27,'קבצי העיצוב המקוריים השתנו.',JSON.stringify(report(work)));const out=path.join(workRoot,'app-1.10.0.asar');await asar.createPackage(work,out);const verify=path.join(workRoot,'verify');await extract(asar,out,verify);if(!ok(verify)||kind(verify)!=='110'||!hasAi(verify))fail(28,'בדיקת app.asar החדש נכשלה.');const uiDir=path.join(res,'core-library');dir(uiDir);fs.copyFileSync(coreUi,path.join(uiDir,'core-library-ui.js'));fs.copyFileSync(visual,path.join(uiDir,'workspace-visual-1.9.0.js'));try{fs.copyFileSync(out,current)}catch(e){try{fs.copyFileSync(backup,current)}catch{}fail(29,'הפעלת 1.10 נכשלה; הגיבוי הוחזר.',e.message)}rm(path.join(res,'app'));fs.writeFileSync(path.join(res,'rambam-bahir-1.10.0.json'),JSON.stringify({version:'1.10.0',home:'AS IS',renderer:'1.6.3 byte-identical',localLibraryCore:true,unifiedEditor:true,encryptedPerUserApi:true,defaultModel:'gpt-5.6-luna',installedAt:new Date().toISOString()},null,2),'utf8');fs.writeFileSync(resultPath,JSON.stringify({ok:true,target,version:'1.10.0',log:logPath},null,2),'utf8');rm(workRoot);if(!quiet){try{const exe=fs.readdirSync(target).find(n=>n.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(n));if(exe){const p=cp.spawn(path.join(target,exe),[],{detached:true,stdio:'ignore'});p.unref()}}catch{}}}
main().then(()=>process.exit(0)).catch(err=>{const code=Number(err.exitCode)||30;log('FATAL '+code+' '+(err.stack||err.message));try{if(!fs.existsSync(resultPath))fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:err.message,log:logPath},null,2),'utf8')}catch{}process.exit(code)});
