(()=>{
if(window.__RB_CORE_110__)return;window.__RB_CORE_110__=true;
const HOME=['ספר המדע','ספר אהבה','ספר זמנים','ספר נשים','ספר קדושה','ספר הפלאה','ספר זרעים','ספר עבודה','ספר הקרבנות','ספר טהרה','ספר נזיקין','ספר קנין','ספר משפטים','ספר שופטים'];
const SCOPES={all:'כל המאגר',shas:'ש״ס',shulchan:'שו״ע ונושאי כליו',tur_tools:'טור ונושאי כליו',tanakh_tools:'תנ״ך ומפרשיו',rambam_commentaries:'מפרשי הרמב״ם',responsa_rishonim:'שו״ת ראשונים'};
let seq=0,pending=new Map(),scope='all',results=[],selected=null,chat=[],chatBusy=false,session='rb'+Date.now();
window.__RB_CORE_RECEIVE__=raw=>{try{const m=typeof raw==='string'?JSON.parse(raw):raw,p=pending.get(m.rid);if(!p)return;pending.delete(m.rid);m.ok?p.resolve(m.data):p.reject(new Error(m.data&&m.data.message||'שגיאה במאגר'));}catch{}};
function req(action,params={}){return new Promise((resolve,reject)=>{const rid='x'+Date.now()+'_'+(++seq);pending.set(rid,{resolve,reject});const q=new URLSearchParams({...params,rid}),a=document.createElement('a');a.href='rambam-core110://'+action+'/?'+q.toString();a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>{if(pending.has(rid)){pending.delete(rid);reject(new Error('המאגר לא החזיר תשובה בזמן'));}},18000);});}
const esc=x=>String(x==null?'':x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function isHome(){const t=document.body?.innerText||'';let n=0;HOME.forEach(x=>{if(t.includes(x))n++});return n>=10;}
function stateKey(){const h=(document.querySelector('h1,h2,h3')?.textContent||document.title||'הלכה').trim(),src=extractSource().slice(0,80);return 'rb110:'+btoa(unescape(encodeURIComponent((h+'|'+src).slice(0,180)))).replace(/=/g,'');}
function loadState(){try{return JSON.parse(localStorage.getItem(stateKey())||'{}')||{}}catch{return{}}}
function saveState(v){try{localStorage.setItem(stateKey(),JSON.stringify(v))}catch{}}
function extractSource(){
 const nodes=[...document.querySelectorAll('p,article,section,div')].filter(e=>!e.closest('#rb-core110')&&!e.closest('#rb-unified110'));
 let best='',score=0;for(const e of nodes){if(e.children.length>8)continue;const t=(e.innerText||'').trim();if(t.length<25||t.length>900)continue;if(/שאל AI|בדוק מקור|הפק Word|תצוגה מקדימה/.test(t))continue;const r=e.getBoundingClientRect();if(r.width<300||r.height<20)continue;const s=t.length+(r.top<420?200:0);if(s>score){score=s;best=t;}}
 return best.replace(/הרמב[״"]ם הבהיר/g,'').trim();
}
function extractComment(){const els=[...document.querySelectorAll('textarea,[contenteditable="true"]')].filter(e=>!e.closest('#rb-core110')&&!e.closest('#rb-unified110'));let b=els.sort((a,c)=>(c.getBoundingClientRect().width*c.getBoundingClientRect().height)-(a.getBoundingClientRect().width*a.getBoundingClientRect().height))[0];return b?(b.value||b.innerText||'').trim():'';}
const style=document.createElement('style');style.id='rb110-style';style.textContent=`
body.rb110-work #rb-core110,body.rb110-work #rb-unified110{display:flex}body.rb110-home #rb-core110,body.rb110-home #rb-unified110{display:none!important}
#rb-core110{display:none;position:fixed;z-index:2147482000;top:122px;right:18px;bottom:52px;width:min(36vw,590px);min-width:430px;direction:rtl;flex-direction:column;background:#fff;border:1px solid #cad5e1;border-radius:12px;box-shadow:0 14px 40px rgba(18,48,80,.16);font-family:Arial,'Noto Sans Hebrew','David',sans-serif;color:#173456;overflow:hidden}
#rb110-head{background:linear-gradient(180deg,#103c69,#0a3159);color:#fff;padding:14px 18px;display:flex;align-items:center;gap:10px}#rb110-head b{font-size:20px}#rb110-dot{width:10px;height:10px;border-radius:50%;background:#43c78a;margin-right:auto}.rb110-tabs{display:flex;border-bottom:1px solid #d8e0e8;background:#fbfcfe}.rb110-tab{flex:1;border:0;border-left:1px solid #e3e8ee;background:#fbfcfe;padding:10px 5px;font-weight:700;color:#25496e;cursor:pointer}.rb110-tab.on{background:#fff8e7;color:#6d511a;border-bottom:3px solid #c59c42}
#rb110-search,#rb110-chat,#rb110-library{display:none;flex:1;min-height:0;flex-direction:column}.rb110-view.on{display:flex}.rb110-query{display:flex;gap:7px;padding:12px}.rb110-query input,.rb110-query textarea{flex:1;border:1px solid #ccd7e2;border-radius:8px;padding:10px 12px;font-size:14px;direction:rtl}.rb110-primary{border:0;background:#123e6d;color:#fff;border-radius:8px;padding:9px 15px;font-weight:800;cursor:pointer}.rb110-secondary{border:1px solid #c9d4df;background:#fff;color:#244a70;border-radius:8px;padding:8px 11px;font-weight:700;cursor:pointer}.rb110-scopes{display:flex;gap:5px;overflow:auto;padding:0 12px 10px}.rb110-scope{flex:0 0 auto;border:1px solid #d8dfe7;background:#fff;border-radius:16px;padding:6px 10px;font-size:12px;cursor:pointer}.rb110-scope.on{background:#fff1cf;border-color:#c39b43;color:#70531b;font-weight:800}
#rb110-searchbody{display:grid;grid-template-columns:.92fr 1.18fr;min-height:0;flex:1;border-top:1px solid #e4e9ee}#rb110-list{overflow:auto;padding:8px;background:#f8fafc;border-left:1px solid #e0e6ec}#rb110-preview{overflow:auto;padding:14px;background:#fff}.rb110-card{border:1px solid #dce3ea;border-right:4px solid #c39a42;border-radius:8px;background:#fff;padding:9px;margin-bottom:7px;cursor:pointer}.rb110-card.on{background:#fff8e6;border-color:#c39a42}.rb110-card b{display:block}.rb110-card small{color:#967329}.rb110-card p{font-size:13px;line-height:1.45;max-height:58px;overflow:hidden;margin:5px 0}.rb110-empty{text-align:center;color:#7a8794;padding:30px 10px}
#rb110-books{overflow:auto;padding:12px}.rb110-book{border-bottom:1px solid #e4e8ed;padding:9px}.rb110-book b{display:block}.rb110-book small{color:#7d6c47}
#rb110-chatlog{flex:1;overflow:auto;padding:12px;background:#f8fafc}.rb110-msg{max-width:92%;padding:10px 12px;border-radius:10px;margin:8px 0;line-height:1.6;white-space:pre-wrap}.rb110-user{margin-right:auto;background:#eaf2fb;border:1px solid #cfdeef}.rb110-ai{background:#fff;border:1px solid #dfd8c5;border-right:4px solid #c39a42}.rb110-ai[contenteditable="true"]:focus{outline:2px solid #d6bb77}.rb110-tools{display:flex;gap:5px;margin-top:7px;flex-wrap:wrap}.rb110-tools button{border:1px solid #d3dbe4;background:#fff;border-radius:6px;padding:5px 8px;cursor:pointer}.rb110-chatbox{display:flex;gap:7px;padding:10px;border-top:1px solid #dfe5eb;background:#fff}.rb110-chatbox textarea{height:58px;resize:none}.rb110-sources{font-size:12px;color:#6d5b33;margin-top:8px;border-top:1px dashed #dfd0aa;padding-top:7px}
#rb-unified110{display:none;position:fixed;z-index:2147481000;top:122px;left:18px;right:calc(min(36vw,590px) + 34px);bottom:52px;direction:rtl;flex-direction:column;background:#fff;border:1px solid #d5dde6;border-radius:12px;box-shadow:0 12px 34px rgba(17,48,79,.10);font-family:Arial,'Noto Sans Hebrew','David',sans-serif;overflow:hidden}.rb110-editorhead{padding:9px 13px;background:#fbfcfe;border-bottom:1px solid #e1e6ec;display:flex;align-items:center;gap:8px}.rb110-editorhead b{color:#153f6b}.rb110-editorhead span{color:#7b8794;font-size:12px}.rb110-edit{flex:1;overflow:auto;padding:30px 42px;font-family:David,'Times New Roman',serif;font-size:18px;line-height:1.85;color:#17283a;outline:none}.rb110-sep{text-align:center;color:#8b671e;font-family:Arial,sans-serif;font-weight:800;font-size:13px;margin:20px 0;padding:5px}.rb110-sep:before,.rb110-sep:after{content:' — ';color:#c6a85d}.rb110-bottom{display:flex;gap:7px;padding:9px 12px;border-top:1px solid #dfe5eb;background:#fbfcfe;align-items:center}.rb110-bottom .push{margin-right:auto}.rb110-notes{max-height:150px;overflow:auto;border-top:1px solid #e2e7ec;padding:8px 14px;background:#fffdf8}.rb110-note{font-size:13px;padding:4px 0;border-bottom:1px dashed #e7deca}.rb110-notebook{width:100%;min-height:90px;border:1px solid #d7dfe7;border-radius:7px;padding:8px;direction:rtl;resize:vertical}
.rb110-hideold{position:fixed!important;left:-20000px!important;top:-20000px!important;opacity:0!important;pointer-events:none!important}.rb110-highlight{background:#fff0a3}
@media(max-width:1200px){#rb-core110{width:43vw;min-width:390px}#rb-unified110{right:calc(43vw + 34px)}}`;
document.head.appendChild(style);
const core=document.createElement('aside');core.id='rb-core110';core.innerHTML=`<div id="rb110-head"><b>מאגר מקומי</b><span>ליבת המקורות של המערכת</span><i id="rb110-dot"></i></div><div class="rb110-tabs"><button class="rb110-tab on" data-v="search">חיפוש מקור</button><button class="rb110-tab" data-v="library">ספריית הספרים</button><button class="rb110-tab" data-v="chat">שאל את המאגר</button></div><div id="rb110-search" class="rb110-view on"><div class="rb110-query"><input id="rb110-q" placeholder="חיפוש במאגר המקומי..."><button id="rb110-go" class="rb110-primary">חפש</button></div><div class="rb110-scopes" id="rb110-scopes"></div><div id="rb110-searchbody"><div id="rb110-list"><div class="rb110-empty">הקלד ביטוי, מקור או מראה מקום.</div></div><div id="rb110-preview"><div class="rb110-empty">בחר תוצאה לתצוגה מקדימה.</div></div></div></div><div id="rb110-library" class="rb110-view"><div class="rb110-query"><button id="rb110-import" class="rb110-primary">העלה ספר למאגר</button><button id="rb110-refresh" class="rb110-secondary">רענן</button></div><div class="rb110-scopes" id="rb110-libscopes"></div><div id="rb110-books"></div></div><div id="rb110-chat" class="rb110-view"><div class="rb110-scopes" id="rb110-chatscopes"></div><div id="rb110-chatlog"><div class="rb110-empty">שיחה רציפה המבוססת קודם על המקורות המקומיים.</div></div><div class="rb110-chatbox"><textarea id="rb110-chatq" placeholder="שאל שאלה; אפשר להמשיך ולשאול על התשובה..."></textarea><button id="rb110-send" class="rb110-primary">שלח</button></div></div>`;document.body.appendChild(core);
const uni=document.createElement('main');uni.id='rb-unified110';uni.innerHTML=`<div class="rb110-editorhead"><b>עריכת ההלכה</b><span>טקסט המקור וההגהה באותו משטח כתיבה</span><button id="rb110-foot" class="rb110-secondary">הערת שוליים</button><button id="rb110-research" class="rb110-secondary">מחברת מחקר</button></div><div id="rb110-edit" class="rb110-edit" contenteditable="true" spellcheck="false"></div><div id="rb110-notes" class="rb110-notes" hidden></div><div id="rb110-notebookwrap" class="rb110-notes" hidden><textarea id="rb110-notebook" class="rb110-notebook" placeholder="מחברת מחקר חופשית..."></textarea></div><div class="rb110-bottom"><button id="rb110-word" class="rb110-primary">שמור הלכה ב־Word</button><button id="rb110-septoggle" class="rb110-secondary">הוסף / מחק „הרמב״ם הבהיר”</button><button id="rb110-save" class="rb110-secondary push">שמור</button></div>`;document.body.appendChild(uni);
const $=id=>document.getElementById(id),edit=$('rb110-edit'),notes=$('rb110-notes'),notebook=$('rb110-notebook');
function scopeButtons(box){Object.entries(SCOPES).forEach(([k,v])=>{const b=document.createElement('button');b.className='rb110-scope'+(k==='all'?' on':'');b.dataset.scope=k;b.textContent=v;box.appendChild(b)});box.onclick=e=>{const b=e.target.closest('.rb110-scope');if(!b)return;scope=b.dataset.scope;document.querySelectorAll('.rb110-scope').forEach(x=>x.classList.toggle('on',x.dataset.scope===scope));};}
scopeButtons($('rb110-scopes'));scopeButtons($('rb110-libscopes'));scopeButtons($('rb110-chatscopes'));
function activate(v){document.querySelectorAll('.rb110-tab').forEach(b=>b.classList.toggle('on',b.dataset.v===v));document.querySelectorAll('.rb110-view').forEach(x=>x.classList.toggle('on',x.id==='rb110-'+v));if(v==='library')loadLibrary();}
document.querySelector('.rb110-tabs').onclick=e=>{const b=e.target.closest('.rb110-tab');if(b)activate(b.dataset.v)};
function initEditor(){const st=loadState(),source=st.source||extractSource(),comment=st.comment||extractComment();edit.innerHTML=st.html||`<div>${esc(source)}</div><div class="rb110-sep" contenteditable="false">הרמב״ם הבהיר</div><div>${esc(comment)||'<br>'}</div>`;notebook.value=st.notebook||'';renderNotes(st.footnotes||[]);}
function currentState(){const old=loadState();return{...old,html:edit.innerHTML,notebook:notebook.value,updatedAt:new Date().toISOString()}}
let saveTimer;edit.addEventListener('input',()=>{clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveState(currentState()),500)});notebook.addEventListener('input',()=>saveState(currentState()));$('rb110-save').onclick=()=>saveState(currentState());
function renderNotes(arr){notes.innerHTML=(arr||[]).map((n,i)=>`<div class="rb110-note"><b>${i+1}.</b> ${esc(n)}</div>`).join('');notes.hidden=!(arr&&arr.length)}
$('rb110-foot').onclick=()=>{const sel=window.getSelection(),txt=sel&&sel.toString().trim();if(!txt)return alert('סמן תחילה טקסט בהגהה');const note=prompt('כתוב את הערת השוליים:');if(!note)return;const st=currentState(),arr=st.footnotes||[];arr.push(note);st.footnotes=arr;try{document.execCommand('insertHTML',false,`<sup>[${arr.length}]</sup>`)}catch{}saveState(st);renderNotes(arr)};
$('rb110-research').onclick=()=>{$('rb110-notebookwrap').hidden=!$('rb110-notebookwrap').hidden;if(!$('rb110-notebookwrap').hidden)notebook.focus()};
$('rb110-septoggle').onclick=()=>{const sep=edit.querySelector('.rb110-sep');if(sep)sep.remove();else{const d=document.createElement('div');d.className='rb110-sep';d.contentEditable='false';d.textContent='הרמב״ם הבהיר';edit.appendChild(d)}saveState(currentState())};
$('rb110-word').onclick=()=>{const body=`<!doctype html><html dir="rtl"><meta charset="utf-8"><style>body{font-family:David;font-size:14pt;line-height:1.7;direction:rtl}.rb110-sep{text-align:center;font-weight:bold;margin:16pt 0}</style><body>${edit.innerHTML}<hr>${notes.innerHTML}</body></html>`,blob=new Blob(['\ufeff',body],{type:'application/msword;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='הלכה - הרמבם הבהיר.doc';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)};
async function doSearch(q=$('rb110-q').value.trim()){if(!q)return;$('rb110-list').innerHTML='<div class="rb110-empty">מחפש...</div>';try{const d=await req('search',{q,scope,limit:70});results=d.results||[];renderResults();if(results.length)preview(0)}catch(e){$('rb110-list').innerHTML='<div class="rb110-empty">'+esc(e.message)+'</div>'}}
function renderResults(){$('rb110-list').innerHTML=results.length?results.map((r,i)=>`<article class="rb110-card" data-i="${i}"><b>${esc(r.he_book||r.book)}</b><small>${esc(r.ref||'')}</small><p>${esc(r.text||'')}</p></article>`).join(''):'<div class="rb110-empty">לא נמצאו תוצאות.</div>'}
async function preview(i){selected=results[i];document.querySelectorAll('.rb110-card').forEach((x,j)=>x.classList.toggle('on',j===i));if(!selected)return;const p=$('rb110-preview');p.innerHTML=`<b>${esc(selected.he_book||selected.book)}</b><div style="color:#967329;margin:5px 0">${esc(selected.ref||'')}</div><div class="rb110-tools"><button id="rb110-copy">העתק</button><button id="rb110-copyref">העתק עם מקור</button><button id="rb110-insert">הכנס להגה</button></div><div style="white-space:pre-wrap;line-height:1.7">${esc(selected.text||'')}</div><div id="rb110-context"></div>`;$('rb110-copy').onclick=()=>navigator.clipboard.writeText(selected.text||'');$('rb110-copyref').onclick=()=>navigator.clipboard.writeText((selected.text||'')+'\n'+(selected.he_book||selected.book)+' '+(selected.ref||''));$('rb110-insert').onclick=()=>{edit.focus();document.execCommand('insertText',false,(selected.text||'')+' ('+(selected.he_book||selected.book)+' '+(selected.ref||'')+')')};try{const c=await req('context',{id:selected.id,radius:2});$('rb110-context').innerHTML=(c.rows||[]).map(x=>`<div style="border-right:3px solid #dfc16e;padding:6px;margin:6px 0">${esc(x.ref||'')} — ${esc(x.text||'')}</div>`).join('')}catch{}}
$('rb110-list').onclick=e=>{const c=e.target.closest('.rb110-card');if(c)preview(+c.dataset.i)};$('rb110-go').onclick=()=>doSearch();$('rb110-q').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();doSearch()}};
async function loadLibrary(){const box=$('rb110-books');box.innerHTML='<div class="rb110-empty">טוען ספרייה...</div>';try{const b=await req('catalog',{scope,limit:800});box.innerHTML=(b||[]).map(x=>`<div class="rb110-book"><b>${esc(x.he_title||x.title)}</b><small>${Number(x.segments||0).toLocaleString()} קטעים</small></div>`).join('')||'<div class="rb110-empty">אין ספרים בקטגוריה.</div>'}catch(e){box.innerHTML='<div class="rb110-empty">'+esc(e.message)+'</div>'}}
$('rb110-refresh').onclick=loadLibrary;$('rb110-import').onclick=()=>{const btn=[...document.querySelectorAll('button')].find(b=>!b.closest('#rb-core110')&&/הוסף מקור|העלה ספר|ייבא מקור/.test((b.textContent||'').trim()));if(btn)btn.click();else alert('כלי הוספת המקור המקורי לא נמצא במסך הנוכחי. פתח את לשונית המקורות והפעל „הוסף מקור”.')};
function legacyPopup(){return [...document.querySelectorAll('div,section')].find(x=>!x.closest('#rb-core110')&&/שיחה חופשית/.test(x.innerText||'')&&x.querySelector('textarea,input'))}
function legacyButton(){return [...document.querySelectorAll('button')].find(b=>!b.closest('#rb-core110')&&/שאל AI|AI שאל|שאל את ה.?AI/.test((b.textContent||'').trim()))}
async function legacyAsk(promptText){const trigger=legacyButton();if(!trigger)throw new Error('מנוע ה־AI הקיים לא נמצא. הגדר API דרך הגדרות ה־AI של המערכת.');trigger.click();await new Promise(r=>setTimeout(r,250));const pop=legacyPopup();if(!pop)throw new Error('חלון ה־AI הקיים לא נפתח');const input=pop.querySelector('textarea,input');const setter=Object.getOwnPropertyDescriptor(Object.getPrototypeOf(input),'value')?.set;setter?setter.call(input,promptText):(input.value=promptText);input.dispatchEvent(new Event('input',{bubbles:true}));const before=(pop.innerText||'').trim();const send=[...pop.querySelectorAll('button')].find(b=>/שלח|שאל/.test((b.textContent||'').trim())&&b!==trigger);if(!send)throw new Error('כפתור שליחת AI לא נמצא');pop.classList.add('rb110-hideold');send.click();return new Promise((resolve,reject)=>{const started=Date.now(),timer=setInterval(()=>{const candidates=[...pop.querySelectorAll('p,div,article')].map(x=>(x.innerText||'').trim()).filter(t=>t.length>80&&!t.includes(promptText.slice(0,80))&&!/שיחה חופשית|כתוב שאלה טבעית/.test(t));const ans=candidates.sort((a,b)=>b.length-a.length)[0];if(ans&&ans!==before){clearInterval(timer);resolve(ans)}else if(Date.now()-started>70000){clearInterval(timer);reject(new Error('לא התקבלה תשובת AI בזמן'))}},600)})}
async function sendChat(){if(chatBusy)return;const q=$('rb110-chatq').value.trim();if(!q)return;chatBusy=true;$('rb110-chatq').value='';chat.push({role:'user',text:q});renderChat();try{const d=await req('search',{q,scope,limit:7}),src=(d.results||[]).slice(0,7),history=chat.slice(-5).map(m=>(m.role==='user'?'שאלה: ':'תשובה: ')+m.text).join('\n'),sources=src.map((r,i)=>`[${i+1}] ${r.he_book||r.book} ${r.ref||''}\n${String(r.text||'').slice(0,800)}`).join('\n\n'),prompt=`אתה מסייע בכתיבת ספר הגהה על הרמב״ם. ענה בעברית ורק על בסיס המקורות המצורפים. ציין [מספר] ליד כל קביעה. אם אין בסיס מספיק אמור זאת.\n\nהמשך השיחה:\n${history}\n\nהשאלה החדשה: ${q}\n\nמקורות מקומיים:\n${sources||'לא נמצאו מקורות.'}`;const ans=await legacyAsk(prompt);chat.push({role:'assistant',text:ans,sources:src})}catch(e){chat.push({role:'assistant',text:'שגיאה: '+e.message,sources:[]})}finally{chatBusy=false;renderChat()}}
function renderChat(){const log=$('rb110-chatlog');log.innerHTML=chat.length?chat.map((m,i)=>m.role==='user'?`<div class="rb110-msg rb110-user">${esc(m.text)}</div>`:`<div class="rb110-msg rb110-ai" contenteditable="true" data-i="${i}">${esc(m.text)}<div class="rb110-tools" contenteditable="false"><button data-act="copy" data-i="${i}">העתק</button><button data-act="mark" data-i="${i}">מארקר</button><button data-act="insert" data-i="${i}">הכנס להגה</button></div>${m.sources&&m.sources.length?`<div class="rb110-sources" contenteditable="false">${m.sources.map((s,j)=>`[${j+1}] ${esc(s.he_book||s.book)} ${esc(s.ref||'')}`).join('<br>')}</div>`:''}</div>`).join(''):'<div class="rb110-empty">שיחה רציפה המבוססת קודם על המקורות המקומיים.</div>';log.scrollTop=log.scrollHeight}
$('rb110-send').onclick=sendChat;$('rb110-chatq').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}};$('rb110-chatlog').onclick=e=>{const b=e.target.closest('button[data-act]');if(!b)return;const m=chat[+b.dataset.i];if(!m)return;if(b.dataset.act==='copy')navigator.clipboard.writeText(m.text);if(b.dataset.act==='insert'){edit.focus();document.execCommand('insertText',false,m.text)}if(b.dataset.act==='mark'){const el=b.closest('.rb110-ai');el.classList.toggle('rb110-highlight')}};
function hideOldAi(){document.querySelectorAll('div,section').forEach(x=>{if(x.closest('#rb-core110'))return;const t=(x.innerText||'').trim();if(/שיחה חופשית.*ללא חיפוש במאגר/.test(t)&&x.querySelector('textarea,input'))x.classList.add('rb110-hideold')})}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.closest('#rb-core110'))return;const t=(b.textContent||'').trim();if(/שאל AI|AI שאל|שאל את ה.?AI/.test(t)){e.preventDefault();e.stopImmediatePropagation();activate('chat');$('rb110-chatq').focus()}},true);
function relabel(){document.querySelectorAll('button,span,label,strong').forEach(el=>{if(el.closest('#rb-core110')||el.closest('#rb-unified110'))return;const t=(el.textContent||'').trim();if(['שאל AI','AI שאל','שאל את ה-AI','שאל את ה AI'].includes(t))el.textContent='שאל את המאגר';if(['HebrewBooks','HEBREWBOOKS','Hebrew Books','Hebrew'].includes(t))el.textContent='מאגר מקומי';if(/הרמב["״]?ם הבהיר/.test(t)&&t!=='הרמב״ם הבהיר')el.textContent=t.replace(/הרמב["״]?ם הבהיר/g,'הרמב״ם הבהיר')})}
function mode(){if(isHome()){document.body.classList.add('rb110-home');document.body.classList.remove('rb110-work');return}document.body.classList.remove('rb110-home');document.body.classList.add('rb110-work');if(!edit.dataset.ready){initEditor();edit.dataset.ready='1'}hideOldAi();relabel()}
setInterval(mode,1000);mode();req('stats').then(s=>{$('rb110-head').querySelector('span').textContent=`${Number(s.books||0).toLocaleString()} ספרים · ${Number(s.segments||0).toLocaleString()} קטעים`}).catch(()=>{});
})();