const fs=require('fs');
const [,,mainPath,packagePath]=process.argv;if(!mainPath||!packagePath)throw new Error('Usage: patch-api-1.10.0.js <main.js> <package.json>');let s=fs.readFileSync(mainPath,'utf8');if(!s.includes('FUNCTIONAL_CORE_110'))throw new Error('FUNCTIONAL_CORE_110 required');if(s.includes('AI_CORE_110'))throw new Error('AI_CORE_110 already applied');const marker='function coreSend181(win,rid,ok,data){';if(!s.includes(marker))throw new Error('coreSend181 marker missing');const h=String.raw`
// AI_CORE_110 — per-user encrypted API; local search itself never calls AI.
function ai110File(){return _nodePath.default.join(_electron.app.getPath('userData'),'rambam-bahir-ai.json');}
function ai110Read(){try{return JSON.parse(_nodeFs.default.readFileSync(ai110File(),'utf8'))||{};}catch{return{};}}
function ai110Key(){const j=ai110Read();if(!j.keyEncrypted)return'';try{return _electron.safeStorage.decryptString(Buffer.from(j.keyEncrypted,'base64'));}catch{return'';}}
function ai110Status(){const j=ai110Read();return{hasKey:Boolean(ai110Key()),model:j.model||'gpt-5.6-luna',encrypted:Boolean(j.keyEncrypted)};}
function ai110Set(key,model){const clean=String(key||'').trim();if(!clean)throw new Error('מפתח API ריק');if(!_electron.safeStorage||!_electron.safeStorage.isEncryptionAvailable())throw new Error('הצפנת Windows אינה זמינה');const allowed=['gpt-5.6-luna','gpt-5.6-terra','gpt-5.6-sol'],m=allowed.includes(model)?model:'gpt-5.6-luna',v={keyEncrypted:_electron.safeStorage.encryptString(clean).toString('base64'),model:m,updatedAt:new Date().toISOString()};_nodeFs.default.writeFileSync(ai110File(),JSON.stringify(v,null,2),'utf8');return ai110Status();}
function ai110Delete(){try{_nodeFs.default.unlinkSync(ai110File());}catch{}return{hasKey:false,model:'gpt-5.6-luna',encrypted:false};}
async function ai110Test(){const key=ai110Key();if(!key)throw new Error('לא הוגדר API');const r=await fetch('https://api.openai.com/v1/models',{headers:{Authorization:'Bearer '+key}});if(!r.ok)throw new Error('בדיקת API נכשלה ('+r.status+')');return{ok:true};}
const ai110Sessions=new Map();function ai110Output(data){try{return(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text||'').join('\n').trim();}catch{return'';}}
async function ai110Chat(sessionId,q,scope){const question=String(q||'').trim().slice(0,1800);if(!question)throw new Error('השאלה ריקה');const found=coreSearch110(question,scope,7).results.slice(0,7),sources=found.map((r,i)=>({n:i+1,book:r.he_book||r.book,ref:r.ref||'',text:String(r.text||'').slice(0,850)})),key=ai110Key(),status=ai110Status();if(!key)return{needsApi:true,answer:'',sources,sessionId};const sid=String(sessionId||('s'+Date.now())).slice(0,80),hist=ai110Sessions.get(sid)||[],src=sources.map(x=>'['+x.n+'] '+x.book+(x.ref?' — '+x.ref:'')+'\n'+x.text).join('\n\n'),recent=hist.slice(-6).map(m=>({role:m.role,content:[{type:'input_text',text:String(m.text||'').slice(0,1600)}]})),input=[{role:'system',content:[{type:'input_text',text:'אתה עוזר מחקר תורני לספר הגהה על משנה תורה. ענה בעברית ורק על יסוד המקורות שסופקו. לכל קביעה מהותית צרף [מספר מקור]. אם אין בסיס מספיק, אמור זאת. אין להמציא מקור או מראה מקום. היה תמציתי.'}]},...recent,{role:'user',content:[{type:'input_text',text:'השאלה:\n'+question+'\n\nמקורות מקומיים:\n'+(src||'לא נמצאו מקורות.')}]}];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({model:status.model,input,reasoning:{effort:'none'},max_output_tokens:650,store:false})});let data={};try{data=await r.json();}catch{}if(!r.ok)throw new Error((data.error&&data.error.message)||('שגיאת API '+r.status));const answer=ai110Output(data)||'לא התקבלה תשובה.';hist.push({role:'user',text:question},{role:'assistant',text:answer});ai110Sessions.set(sid,hist.slice(-8));return{needsApi:false,answer,sources,sessionId:sid,model:status.model,usage:data.usage||null};}
function ai110Handle(win,event,url){if(!String(url||'').startsWith('rambam-ai110://'))return false;event.preventDefault();let rid='';try{const u=new URL(url);rid=u.searchParams.get('rid')||'';const a=u.hostname||u.pathname.replace(/^\//,'');if(a==='status'){coreSend181(win,rid,true,ai110Status());return true}if(a==='set'){coreSend181(win,rid,true,ai110Set(u.searchParams.get('key')||'',u.searchParams.get('model')||''));return true}if(a==='delete'){coreSend181(win,rid,true,ai110Delete());return true}if(a==='clear'){ai110Sessions.delete(u.searchParams.get('session')||'');coreSend181(win,rid,true,{ok:true});return true}if(a==='test'){ai110Test().then(d=>coreSend181(win,rid,true,d)).catch(e=>coreSend181(win,rid,false,{message:String(e&&e.message||e)}));return true}if(a==='chat'){ai110Chat(u.searchParams.get('session')||'',u.searchParams.get('q')||'',u.searchParams.get('scope')||'all').then(d=>coreSend181(win,rid,true,d)).catch(e=>coreSend181(win,rid,false,{message:String(e&&e.message||e)}));return true}throw new Error('Unknown AI action')}catch(e){coreSend181(win,rid,false,{message:String(e&&e.message||e)});return true}}
_electron.app.on('browser-window-created',(_e,w)=>{w.webContents.on('will-navigate',(event,url)=>{ai110Handle(w,event,url);});});
`;
s=s.replace(marker,h+'\n'+marker);fs.writeFileSync(mainPath,s,'utf8');const pkg=JSON.parse(fs.readFileSync(packagePath,'utf8'));pkg.version='1.10.0';fs.writeFileSync(packagePath,JSON.stringify(pkg,null,2),'utf8');console.log('Applied AI_CORE_110.');
