const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),cp=require('child_process');
const payload=process.argv[2],quiet=process.argv.includes('--quiet'),selftest=process.argv.includes('--selftest');
const logPath=path.join(os.tmpdir(),'HaYad-1.8.2-install.log'),resultPath=path.join(os.tmpdir(),'HaYad-1.8.2-result.json');
function log(m){try{fs.appendFileSync(logPath,'['+new Date().toISOString()+'] '+m+'\n','utf8')}catch{}}
function fail(code,msg,extra){const d={ok:false,code,message:msg,extra:extra||null,log:logPath};log('ERROR '+code+': '+msg+(extra?' / '+extra:''));try{fs.writeFileSync(resultPath,JSON.stringify(d,null,2),'utf8')}catch{}const e=new Error(msg);e.exitCode=code;throw e}
function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}function dir(p){fs.mkdirSync(p,{recursive:true})}function rm(p){try{fs.rmSync(p,{recursive:true,force:true})}catch{}}
function candidates(){const a=[];for(const r of [process.env.LOCALAPPDATA,process.env.ProgramFiles,process.env['ProgramFiles(x86)']].filter(Boolean))a.push(path.join(r,'hayad-hahazaka'),path.join(r,'Programs','hayad-hahazaka'),path.join(r,'Programs','HaYad-HaHazaka'),path.join(r,'Programs','היד החזקה'),path.join(r,'HaYad-HaHazaka'),path.join(r,'היד החזקה'));return[...new Set(a)]}
function rendererOk(d){const e={[path.join('dist','assets','index.js')]:'e2a301bad496d87490eaceb091204d2287fa60f00c5d22341403e6f8daa69e76',[path.join('dist','assets','index.css')]:'6df2817f475b85236d7c4764d1fa2339673b3d827cd6442fbce042b5dbcefc37',[path.join('dist','index.html')]:'74e52686fc6f255043062277f385b45cd85e2fdd16abc42dc00afbe18913de24'};for(const [r,w] of Object.entries(e)){const p=path.join(d,r);if(!fs.existsSync(p)||sha(p)!==w){log('UI hash mismatch '+r);return false}}return true}
function kindOf(d){const p=path.join(d,'dist-electron','main.js');if(!fs.existsSync(p))return'unknown';const t=fs.readFileSync(p,'utf8');if(t.includes('LOCAL_CORE_181'))return'181';if(t.includes('LOCAL_CORE_180'))return'180';if(t.includes('LOCAL_CORPUS_176'))return'176';if(t.includes("_electron.ipcMain.handle('knowledge:list', () => store.read().knowledge)")&&t.includes('function ensureMaster() {'))return'163';return'unknown'}
function stopApp(t){try{for(const f of fs.readdirSync(t,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(x.name))){try{cp.execFileSync('taskkill.exe',['/IM',f.name,'/F','/T'],{windowsHide:true,stdio:'ignore'})}catch{}}}catch{}}
function corpus(res){const lib=path.join(res,'local-library'),sqlite=path.join(lib,'sqlite3.exe'),db=path.join(lib,'torah-library.sqlite');if(!fs.existsSync(sqlite)||!fs.existsSync(db))fail(17,'המאגר המקומי אינו מותקן. יש להתקין תחילה את גרסה 1.7.5 המלאה.');let q='';try{q=cp.execFileSync(sqlite,['-readonly',db,'PRAGMA quick_check;'],{windowsHide:true,encoding:'utf8',timeout:120000}).trim()}catch(e){fail(18,'לא ניתן לבדוק את המאגר המקומי.',e.message)}if(q!=='ok')fail(18,'בדיקת תקינות המאגר נכשלה.',q);let s={books:0,segments:0};try{const raw=cp.execFileSync(sqlite,['-readonly','-json',db,"SELECT (SELECT count(*) FROM books) AS books,(SELECT count(*) FROM segments) AS segments;"],{windowsHide:true,encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024}).trim();s=(raw?JSON.parse(raw):[])[0]||s}catch(e){fail(18,'לא ניתן לקרוא את נתוני המאגר.',e.message)}if(+s.books<100||+s.segments<10000)fail(18,'המאגר המקומי קטן או פגום.',JSON.stringify(s));return{books:+s.books,segments:+s.segments}}
function run(node,script,main,pkg,code,label){try{const out=cp.execFileSync(node,[script,main,pkg],{windowsHide:true,encoding:'utf8',maxBuffer:32*1024*1024});log(label+' OK '+String(out||'').trim())}catch(e){fail(code,label+' נכשל.',[e.message,e.stdout&&String(e.stdout),e.stderr&&String(e.stderr)].filter(Boolean).join('\n').slice(0,5000))}}
async function extract(asar,file,to){dir(to);await Promise.resolve(asar.extractAll(file,to))}
async function main(){fs.writeFileSync(logPath,'['+new Date().toISOString()+'] Starting HaYad 1.8.2 directory-app repair\n','utf8');if(!payload||!fs.existsSync(payload))fail(2,'Payload folder missing',payload||'');
const asarDir=path.join(payload,'asar-tool','node_modules','@electron','asar'),p176=path.join(payload,'patch-main-1.7.6.cjs'),p181=path.join(payload,'patch-core-1.8.1.cjs'),ui=path.join(payload,'core-library-ui.js');for(const p of[asarDir,p176,p181,ui])if(!fs.existsSync(p))fail(3,'Installer payload incomplete',p);const asar=require(asarDir),node=process.execPath;
if(selftest){const a=fs.readFileSync(p181,'utf8'),u=fs.readFileSync(ui,'utf8');if(!a.includes('LOCAL_CORE_181')||!a.includes('core-library-ui.js'))fail(4,'Core backend assertions missing');if(!u.includes('rb-core-bar')||!u.includes('ספריית הספרים')||!u.includes('שאל במאגר'))fail(5,'Core UI assertions missing');log('SELFTEST OK');return}
let target=null;for(const p of candidates())if(fs.existsSync(path.join(p,'resources','app.asar'))){target=p;break}if(!target)fail(11,'לא נמצאה התקנת היד החזקה קיימת.');stopApp(target);const res=path.join(target,'resources'),c=corpus(res),current=path.join(res,'app.asar'),original=path.join(res,'app-1.6.3-original.asar'),pre=path.join(res,'app-before-1.8.2.asar'),liveDir=path.join(res,'app'),oldLive=path.join(res,'app-before-1.8.2-dir'),workRoot=path.join(os.tmpdir(),'HaYad182Work');rm(workRoot);dir(workRoot);try{fs.copyFileSync(current,pre)}catch(e){fail(30,'לא ניתן ליצור גיבוי של app.asar.',e.message)}
let source=null,kind='unknown';for(const candidate of [original,current,pre].filter((v,i,a)=>a.indexOf(v)===i&&fs.existsSync(v))){const d=path.join(workRoot,'inspect-'+crypto.randomBytes(3).toString('hex'));try{await extract(asar,candidate,d);if(!rendererOk(d)){log('Skipped ASAR with UI mismatch '+candidate);continue}const k=kindOf(d);log('Candidate '+candidate+' kind='+k);if(['181','176','163'].includes(k)){source=candidate;kind=k;break}if(k==='180')log('Skipping legacy 1.8.0 backend')}catch(e){log('Candidate inspect failed '+candidate+': '+e.message)}finally{rm(d)}}
if(!source)fail(12,'לא נמצאה חבילת בסיס תקינה עם ממשק 1.6.3 המאושר. לא בוצע שינוי.');const work=path.join(workRoot,'app');try{await extract(asar,source,work)}catch(e){fail(29,'פתיחת חבילת הבסיס נכשלה.',e.message)}if(!rendererOk(work))fail(13,'נעילת העיצוב נכשלה לפני העדכון.');const mainPath=path.join(work,'dist-electron','main.js'),pkgPath=path.join(work,'package.json');if(kind==='163')run(node,p176,mainPath,pkgPath,22,'הכנת backend 1.7.6');if(kind!=='181')run(node,p181,mainPath,pkgPath,23,'הטמעת Core Library 1.8.1');if(!rendererOk(work))fail(14,'קבצי ה-UI המקוריים השתנו. העדכון בוטל.');if(kindOf(work)!=='181')fail(15,'שכבת Core Library לא נוספה.');try{const j=JSON.parse(fs.readFileSync(pkgPath,'utf8'));j.version='1.8.2';fs.writeFileSync(pkgPath,JSON.stringify(j,null,2),'utf8')}catch(e){fail(24,'עדכון מספר הגרסה נכשל.',e.message)}
// Deploy as resources/app directory. Electron loads this ahead of app.asar; app.asar stays untouched as rollback.
rm(oldLive);if(fs.existsSync(liveDir)){try{fs.renameSync(liveDir,oldLive)}catch(e){fail(33,'לא ניתן לגבות את resources\\app הקיים.',e.message)}}try{fs.cpSync(work,liveDir,{recursive:true,force:true})}catch(e){rm(liveDir);if(fs.existsSync(oldLive))try{fs.renameSync(oldLive,liveDir)}catch{}fail(34,'פריסת resources\\app נכשלה.',e.message)}
const uiDir=path.join(res,'core-library');try{dir(uiDir);fs.copyFileSync(ui,path.join(uiDir,'core-library-ui.js'))}catch(e){rm(liveDir);if(fs.existsSync(oldLive))try{fs.renameSync(oldLive,liveDir)}catch{}fail(31,'התקנת שכבת המאגר החזותית נכשלה.',e.message)}
if(!rendererOk(liveDir)){rm(liveDir);if(fs.existsSync(oldLive))try{fs.renameSync(oldLive,liveDir)}catch{}fail(20,'בדיקת קבצי הממשק לאחר הפריסה נכשלה; בוצע rollback.')}if(kindOf(liveDir)!=='181'){rm(liveDir);if(fs.existsSync(oldLive))try{fs.renameSync(oldLive,liveDir)}catch{}fail(21,'בדיקת Backend לאחר הפריסה נכשלה; בוצע rollback.')}const uiFinal=path.join(uiDir,'core-library-ui.js');if(!fs.existsSync(uiFinal)||!fs.readFileSync(uiFinal,'utf8').includes('rb-core-bar'))fail(32,'בדיקת שכבת המאגר החזותית נכשלה.');
const meta={version:'1.8.2',base:'1.6.3',renderer:'byte-identical',deployment:'resources/app',coreLibrary:true,books:c.books,segments:c.segments,sourceKind:kind,uiFile:uiFinal,installedAt:new Date().toISOString()};fs.writeFileSync(path.join(res,'rambam-bahir-1.8.2.json'),JSON.stringify(meta,null,2),'utf8');rm(workRoot);fs.writeFileSync(resultPath,JSON.stringify({ok:true,target,...meta,log:logPath},null,2),'utf8');log('SUCCESS 1.8.2');if(!quiet){try{const exe=fs.readdirSync(target).find(n=>n.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(n));if(exe){const p=cp.spawn(path.join(target,exe),[],{detached:true,stdio:'ignore'});p.unref()}}catch(e){log('Launch skipped '+e.message)}}}
main().then(()=>process.exit(0)).catch(err=>{const code=Number(err.exitCode)||30;const extra=err.stack||err.message;log('FATAL '+code+': '+extra);try{if(!fs.existsSync(resultPath))fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:err.message,stack:extra,log:logPath},null,2),'utf8')}catch{}process.exit(code)});
