const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),cp=require('child_process');
const payload=process.argv[2],quiet=process.argv.includes('--quiet'),selftest=process.argv.includes('--selftest');
const logPath=path.join(os.tmpdir(),'HaYad-1.9.1-install.log'),resultPath=path.join(os.tmpdir(),'HaYad-1.9.1-result.json');
function log(m){try{fs.appendFileSync(logPath,'['+new Date().toISOString()+'] '+m+'\n','utf8')}catch{}}
function fail(code,msg,extra){const d={ok:false,code,message:msg,extra:extra||null,log:logPath};log('ERROR '+code+': '+msg+(extra?' / '+extra:''));try{fs.writeFileSync(resultPath,JSON.stringify(d,null,2),'utf8')}catch{}const e=new Error(msg);e.exitCode=code;throw e}
function sha(f){return crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')}
function dir(p){fs.mkdirSync(p,{recursive:true})}function rm(p){try{fs.rmSync(p,{recursive:true,force:true})}catch{}}
const UI_HASHES={
  [path.join('dist','assets','index.js')]:'e2a301bad496d87490eaceb091204d2287fa60f00c5d22341403e6f8daa69e76',
  [path.join('dist','assets','index.css')]:'6df2817f475b85236d7c4764d1fa2339673b3d827cd6442fbce042b5dbcefc37',
  [path.join('dist','index.html')]:'74e52686fc6f255043062277f385b45cd85e2fdd16abc42dc00afbe18913de24'
};
function rendererReport(d){const bad=[];for(const [r,w] of Object.entries(UI_HASHES)){const p=path.join(d,r),a=fs.existsSync(p)?sha(p):'MISSING';if(a!==w)bad.push({file:r,expected:w,actual:a})}return bad}
function rendererOk(d){const bad=rendererReport(d);if(bad.length)log('UI HASH MISMATCH '+JSON.stringify(bad));return bad.length===0}
function candidates(){const a=[];for(const r of [process.env.LOCALAPPDATA,process.env.ProgramFiles,process.env['ProgramFiles(x86)']].filter(Boolean))a.push(path.join(r,'hayad-hahazaka'),path.join(r,'Programs','hayad-hahazaka'),path.join(r,'Programs','HaYad-HaHazaka'),path.join(r,'Programs','היד החזקה'),path.join(r,'HaYad-HaHazaka'),path.join(r,'היד החזקה'));return[...new Set(a)]}
function kindOf(d){const p=path.join(d,'dist-electron','main.js');if(!fs.existsSync(p))return'unknown';const t=fs.readFileSync(p,'utf8');if(t.includes('WORKSPACE_VISUAL_190'))return'190';if(t.includes('LOCAL_CORE_181'))return'181';if(t.includes('LOCAL_CORPUS_176'))return'176';if(t.includes("_electron.ipcMain.handle('knowledge:list', () => store.read().knowledge)")&&t.includes('function ensureMaster() {'))return'163';return'unknown'}
function stopApp(t){try{for(const f of fs.readdirSync(t,{withFileTypes:true}).filter(x=>x.isFile()&&x.name.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(x.name))){try{cp.execFileSync('taskkill.exe',['/IM',f.name,'/F','/T'],{windowsHide:true,stdio:'ignore'})}catch{}}}catch{}}
function corpus(res){const lib=path.join(res,'local-library'),sqlite=path.join(lib,'sqlite3.exe'),db=path.join(lib,'torah-library.sqlite');if(!fs.existsSync(sqlite)||!fs.existsSync(db))fail(17,'Local corpus is not installed. Install the full corpus package first.');let q='';try{q=cp.execFileSync(sqlite,['-readonly',db,'PRAGMA quick_check;'],{windowsHide:true,encoding:'utf8',timeout:120000}).trim()}catch(e){fail(18,'Local corpus integrity check failed.',e.message)}if(q!=='ok')fail(18,'Local corpus integrity check failed.',q);let s={books:0,segments:0};try{const raw=cp.execFileSync(sqlite,['-readonly','-json',db,"SELECT (SELECT count(*) FROM books) AS books,(SELECT count(*) FROM segments) AS segments;"],{windowsHide:true,encoding:'utf8',timeout:120000,maxBuffer:8*1024*1024}).trim();s=(raw?JSON.parse(raw):[])[0]||s}catch(e){fail(18,'Cannot read local corpus statistics.',e.message)}if(+s.books<100||+s.segments<10000)fail(18,'Local corpus is incomplete.',JSON.stringify(s));return{books:+s.books,segments:+s.segments}}
function run(node,script,main,pkg,code,label){try{const out=cp.execFileSync(node,[script,main,pkg],{windowsHide:true,encoding:'utf8',maxBuffer:32*1024*1024});log(label+' OK '+String(out||'').trim())}catch(e){fail(code,label+' failed.',[e.message,e.stdout&&String(e.stdout),e.stderr&&String(e.stderr)].filter(Boolean).join('\n').slice(0,7000))}}
async function extract(asar,file,to){dir(to);await Promise.resolve(asar.extractAll(file,to))}
async function main(){fs.writeFileSync(logPath,'['+new Date().toISOString()+'] Starting HaYad 1.9.1 real app.asar activation\n','utf8');if(!payload||!fs.existsSync(payload))fail(2,'Payload folder missing',payload||'');
const asarDir=path.join(payload,'asar-tool','node_modules','@electron','asar'),p176=path.join(payload,'patch-main-1.7.6.cjs'),p181=path.join(payload,'patch-core-1.8.1.cjs'),p190=path.join(payload,'patch-visual-1.9.0.cjs'),coreUi=path.join(payload,'core-library-ui.js'),visual=path.join(payload,'workspace-visual-1.9.0.js');for(const p of[asarDir,p176,p181,p190,coreUi,visual])if(!fs.existsSync(p))fail(3,'Installer payload incomplete',p);const asar=require(asarDir),node=process.execPath;
if(selftest){const a=fs.readFileSync(p190,'utf8'),v=fs.readFileSync(visual,'utf8'),c=fs.readFileSync(coreUi,'utf8');if(!a.includes('WORKSPACE_VISUAL_190'))fail(4,'Workspace hook missing');if(!v.includes('HOME_BOOKS')||!v.includes('rb-home-locked-190')||!v.includes('שאל את המאגר'))fail(5,'Workspace visual assertions missing');if(!c.includes('rb-core-bar')||!c.includes('ספריית הספרים'))fail(6,'Core Library assertions missing');log('SELFTEST OK');return}
let target=null;for(const p of candidates())if(fs.existsSync(path.join(p,'resources','app.asar'))){target=p;break}if(!target)fail(11,'Existing HaYad installation was not found.');stopApp(target);
const res=path.join(target,'resources'),c=corpus(res),current=path.join(res,'app.asar'),original=path.join(res,'app-1.6.3-original.asar'),backup=path.join(res,'app-before-1.9.1.asar'),workRoot=path.join(os.tmpdir(),'HaYad191Work');rm(workRoot);dir(workRoot);
try{fs.copyFileSync(current,backup)}catch(e){fail(30,'Cannot create safety backup of current app.asar.',e.message)}
const sourceCandidates=[original,current,path.join(res,'app-before-1.8.1.asar'),path.join(res,'app-before-1.8.3.asar')].filter((v,i,a)=>a.indexOf(v)===i&&fs.existsSync(v));let source=null,kind='unknown';
for(const candidate of sourceCandidates){const d=path.join(workRoot,'inspect-'+crypto.randomBytes(3).toString('hex'));try{await extract(asar,candidate,d);if(!rendererOk(d)){log('Skipped source due to renderer mismatch '+candidate);continue}const k=kindOf(d);log('Candidate '+candidate+' kind='+k);if(['163','176','181','190'].includes(k)){source=candidate;kind=k;break}}catch(e){log('Candidate inspect failed '+candidate+': '+e.message)}finally{rm(d)}}
if(!source)fail(12,'No verified 1.6.3-renderer base ASAR was found. Current app.asar was not changed.');
const work=path.join(workRoot,'app');try{await extract(asar,source,work)}catch(e){fail(34,'Cannot extract verified base ASAR.',e.message)}let bad=rendererReport(work);if(bad.length)fail(20,'Verified base unexpectedly failed UI hash check.',JSON.stringify(bad));
const mainPath=path.join(work,'dist-electron','main.js'),pkgPath=path.join(work,'package.json');let k=kindOf(work);if(k==='163'){run(node,p176,mainPath,pkgPath,22,'Prepare local corpus backend');k=kindOf(work)}if(k==='176'){run(node,p181,mainPath,pkgPath,23,'Install Core Library backend');k=kindOf(work)}if(k==='181'){run(node,p190,mainPath,pkgPath,24,'Install workspace visual hook');k=kindOf(work)}if(k!=='190')fail(25,'Workspace backend verification failed.',k);
bad=rendererReport(work);if(bad.length)fail(14,'Renderer files changed during backend-only patch.',JSON.stringify(bad));try{const j=JSON.parse(fs.readFileSync(pkgPath,'utf8'));j.version='1.9.1';fs.writeFileSync(pkgPath,JSON.stringify(j,null,2),'utf8')}catch(e){fail(26,'Version metadata update failed.',e.message)}
const out=path.join(workRoot,'app-1.9.1.asar');try{await asar.createPackage(work,out)}catch(e){fail(27,'Creating new app.asar failed.',e.message)}const verify=path.join(workRoot,'verify');try{await extract(asar,out,verify)}catch(e){fail(28,'Cannot verify newly created app.asar.',e.message)}bad=rendererReport(verify);if(bad.length)fail(29,'New app.asar changed approved renderer bytes.',JSON.stringify(bad));if(kindOf(verify)!=='190')fail(21,'New app.asar does not contain Workspace/Core backend.',kindOf(verify));
const uiDir=path.join(res,'core-library');try{dir(uiDir);fs.copyFileSync(coreUi,path.join(uiDir,'core-library-ui.js'));fs.copyFileSync(visual,path.join(uiDir,'workspace-visual-1.9.0.js'))}catch(e){fail(31,'Cannot install external Core/visual files.',e.message)}
try{fs.copyFileSync(out,current)}catch(e){try{fs.copyFileSync(backup,current)}catch{}fail(19,'Replacing active app.asar failed; original restored.',e.message)}
const final=path.join(workRoot,'final');try{await extract(asar,current,final)}catch(e){try{fs.copyFileSync(backup,current)}catch{}fail(32,'Installed app.asar cannot be reopened; previous ASAR restored.',e.message)}bad=rendererReport(final);if(bad.length||kindOf(final)!=='190'){try{fs.copyFileSync(backup,current)}catch{}fail(33,'Installed app.asar verification failed; previous ASAR restored.',JSON.stringify({bad,kind:kindOf(final)}))}
// Remove stale resources/app experiments: Electron loads app.asar before app, and leaving this folder creates confusion during diagnostics.
try{rm(path.join(res,'app'))}catch{}
const meta={version:'1.9.1',homeScreen:'locked-as-is',renderer:'byte-identical-1.6.3',activePackage:'resources/app.asar',workspaceVisual:true,coreLibrary:true,books:c.books,segments:c.segments,installedAt:new Date().toISOString()};fs.writeFileSync(path.join(res,'rambam-bahir-1.9.1.json'),JSON.stringify(meta,null,2),'utf8');rm(workRoot);fs.writeFileSync(resultPath,JSON.stringify({ok:true,target,...meta,log:logPath},null,2),'utf8');log('SUCCESS 1.9.1 active app.asar replaced and verified');if(!quiet){try{const exe=fs.readdirSync(target).find(n=>n.toLowerCase().endsWith('.exe')&&!/unins|uninstall|elevate/i.test(n));if(exe){const p=cp.spawn(path.join(target,exe),[],{detached:true,stdio:'ignore'});p.unref()}}catch(e){log('Launch skipped '+e.message)}}}
main().then(()=>process.exit(0)).catch(err=>{const code=Number(err.exitCode)||30;log('FATAL '+code+': '+(err.stack||err.message));try{if(!fs.existsSync(resultPath))fs.writeFileSync(resultPath,JSON.stringify({ok:false,code,message:err.message,stack:err.stack||err.message,log:logPath},null,2,'utf8')}catch{}process.exit(code)});