import React,{useEffect,useState}from'react';

type R={id:number;book:string;he_book:string;category:string;ref:string;text:string;source:string};
const cats=[['all','הכל'],['tanakh','תנ״ך'],['mishnah','משנה'],['tosefta','תוספתא'],['bavli','בבלי'],['yerushalmi','ירושלמי'],['rambam','רמב״ם'],['rishonim','ראשונים'],['tur','טור'],['shulchan_arukh','שולחן ערוך'],['midrash','מדרש'],['responsa','שו״ת'],['halakhah','הלכה'],['thought','מחשבה'],['private','פרטי']];

function Settings({close}:{close:()=>void}){
 const[key,setKey]=useState(''),[model,setModel]=useState('gpt-5.6-luna'),[has,setHas]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{window.hayad.getAI().then(x=>{setModel(x.model);setHas(x.hasKey)})},[]);
 async function save(){await window.hayad.saveAI({apiKey:key,model});setHas(true);setKey('');setMsg('נשמר מוצפן במחשב זה בלבד')}
 async function test(){setMsg('בודק...');const x=await window.hayad.testAI({apiKey:key});setMsg(x.ok?'החיבור תקין ✓':x.error)}
 return <div className="modal"><div className="settings"><button className="x" onClick={close}>×</button><h2>הגדרות AI למשתמש זה</h2><p>המאגר עובד גם בלי API. המפתח דרוש רק לסיכום AI והוא נשמר מוצפן ב-Windows.</p><label>OpenAI API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder={has?'מפתח כבר שמור — הזן רק כדי להחליף':'sk-...'}/></label><label>מודל<select value={model} onChange={e=>setModel(e.target.value)}><option value="gpt-5.6-luna">GPT-5.6 Luna — חסכוני</option><option value="gpt-5.6-terra">GPT-5.6 Terra — מאוזן</option><option value="gpt-5.6-sol">GPT-5.6 Sol — חזק</option></select></label><div className="row"><button onClick={test}>בדוק חיבור</button><button className="gold" onClick={save}>שמור</button><button onClick={async()=>{await window.hayad.deleteAI();setHas(false);setMsg('המפתח נמחק')}}>מחק מפתח</button></div><b>{msg}</b></div></div>
}

function Library({back,settings}:{back:()=>void;settings:()=>void}){
 const[mode,setMode]=useState<'search'|'chat'>('chat'),[q,setQ]=useState(''),[cat,setCat]=useState('all'),[res,setRes]=useState<R[]>([]),[sel,setSel]=useState<R|null>(null),[ctx,setCtx]=useState<any>(null),[ms,setMs]=useState<number|null>(null),[stats,setStats]=useState<any>(null),[answer,setAnswer]=useState(''),[chatSources,setChatSources]=useState<R[]>([]),[busy,setBusy]=useState(false),[aiMsg,setAiMsg]=useState('');
 useEffect(()=>{window.hayad.stats().then(setStats)},[]);
 async function go(){if(!q.trim())return;const x=await window.hayad.search(q,cat,80);setRes(x.results);setMs(x.elapsedMs);setSel(null)}
 async function ask(useAI=false){if(!q.trim())return;setBusy(true);setAiMsg('');try{const x=await window.hayad.chat(q,cat,useAI);setAnswer(x.answer);setChatSources(x.sources||[]);setMs(x.elapsedMs);if(x.aiError)setAiMsg('סיכום AI לא הופעל: '+x.aiError)}finally{setBusy(false)}}
 async function pick(r:R){setSel(r);setCtx(await window.hayad.context(r.id,r.source,6))}
 async function add(){const x=await window.hayad.importSource();if(x?.ok){alert(`נוסף ${x.title}: ${x.count} קטעים`);setStats(await window.hayad.stats())}}
 const copyAnswer=()=>navigator.clipboard.writeText(answer);
 const copyAll=()=>navigator.clipboard.writeText(answer+'\n\nמקורות:\n'+chatSources.map((s,i)=>`[${i+1}] ${s.he_book||s.book}, ${s.ref}\n${s.text}`).join('\n\n'));
 return <div><header><button onClick={back}>← חזרה</button><div><strong>המאגר התורני המקומי</strong><small>{stats?`${stats.builtIn.books} ספרים · ${Number(stats.builtIn.segments).toLocaleString()} קטעים · OFFLINE`:'טוען...'}</small></div><span/><button onClick={add}>＋ ספר / OCR</button><button onClick={settings}>⚙ API</button></header>
 <div className="modeTabs"><button className={mode==='chat'?'on':''} onClick={()=>setMode('chat')}>💬 שאל את המאגר</button><button className={mode==='search'?'on':''} onClick={()=>setMode('search')}>🔎 חיפוש מדויק</button></div>
 <div className="search"><div className="line"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(mode==='chat'?ask(false):go())} placeholder={mode==='chat'?'שאל שאלה: איפה הרמב״ם כותב... / מה המקור ל...':'איפה כתוב... / הדבק ציטוט'}/>{mode==='chat'?<><button className="gold" disabled={busy} onClick={()=>ask(false)}>{busy?'בודק...':'שאל LOCAL'}</button><button disabled={busy} onClick={()=>ask(true)}>סכם עם AI</button></>:<button className="gold" onClick={go}>חפש</button>}</div><div className="chips">{cats.map(c=><button className={cat===c[0]?'on':''} key={c[0]} onClick={()=>setCat(c[0])}>{c[1]}</button>)}</div>{ms!==null&&<small>{mode==='chat'?`התשובה נבנתה ב-${ms}ms`:`נמצאו ${res.length} תוצאות ב-${ms}ms`} {mode==='search'?'— ללא אינטרנט':''}</small>}{aiMsg&&<small className="warn">{aiMsg}</small>}</div>
 {mode==='search'?<main><section className="results">{res.map((r,i)=><button className={'result '+(sel===r?'chosen':'')} key={i} onClick={()=>pick(r)}><b>{r.he_book||r.book}</b><em>{r.ref}</em><p>{r.text.slice(0,230)}</p></button>)}</section><Preview sel={sel} ctx={ctx}/></main>:<main className="chatMain"><section className="chatAnswer">{answer?<><div className="answerTools"><button onClick={copyAnswer}>העתק תשובה</button><button className="gold" onClick={copyAll}>העתק עם מקורות</button></div><div className="question">{q}</div><article>{answer}</article></>:<div className="empty"><h2>שאל את המאגר</h2><p>החיפוש נעשה קודם במאגר המקומי. אין צורך באינטרנט ואין צורך ב-AI כדי לאתר מקור.</p><p>לסיכום פרשני אפשר ללחוץ „סכם עם AI” — ורק המקורות שנמצאו יישלחו למודל.</p></div>}</section><section className="chatSources"><h3>מקורות שעליהם מבוססת התשובה</h3>{chatSources.map((r,i)=><button className={'result '+(sel===r?'chosen':'')} key={i} onClick={()=>pick(r)}><b>[{i+1}] {r.he_book||r.book}</b><em>{r.ref}</em><p>{r.text.slice(0,260)}</p></button>)}{sel&&<div className="miniPreview"><Preview sel={sel} ctx={ctx}/></div>}</section></main>}
 </div>
}

function Preview({sel,ctx}:{sel:R|null;ctx:any}){return <section className="preview">{sel?<><div className="pvhead"><div><h2>{sel.he_book||sel.book}</h2><b>{sel.ref}</b></div><div><button onClick={()=>navigator.clipboard.writeText(sel.text)}>העתק</button><button className="gold" onClick={()=>navigator.clipboard.writeText(`${sel.text}\n(${sel.ref})`)}>העתק עם מקור</button></div></div><article>{ctx?.rows?.map((x:any)=><p className={x.id===ctx.selected.id?'focus':''} key={x.id}>{x.text}</p>)}</article></>:<div className="empty"><h2>תצוגה מקדימה</h2><p>בחר מקור והוא ייפתח כאן בגלילה.</p></div>}</section>}

function App(){const[page,setPage]=useState<'home'|'library'|'work'>('home'),[settings,setSettings]=useState(false),[master,setMaster]=useState(''),[draft,setDraft]=useState('');useEffect(()=>{window.hayad.loadDraft().then(setDraft)},[]);async function load(){const x=await window.hayad.pickMaster();if(x?.ok){setMaster(x.text);setPage('work')}}return <>{settings&&<Settings close={()=>setSettings(false)}/>} {page==='home'?<div className="home"><h1>הי״ד החזקה - רבי משה בן מימון</h1><div className="homeBtns"><button onClick={load}>טען מאסטר</button><button className="gold" onClick={()=>setPage('library')}>💬 שאל את המאגר</button><button onClick={()=>setSettings(true)}>⚙ הגדרות API</button></div><div className="welcome"><h2>מכון הרמב״ם הבהיר</h2><p>עריכה, הגהה ומחקר מקומי. המאגר עובד גם ללא אינטרנט.</p></div></div>:page==='library'?<Library back={()=>setPage('home')} settings={()=>setSettings(true)}/>:<div><header><button onClick={()=>setPage('home')}>⌂ שער</button><strong>סביבת הגהה</strong><span/><button className="gold" onClick={()=>setPage('library')}>💬 שאל את המאגר</button><button onClick={()=>setSettings(true)}>⚙ API</button></header><div className="work"><section><h2>לשון הרמב״ם</h2><article className="master">{master}</article></section><section><h2>— הרמב״ם הבהיר —</h2><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="כתוב כאן את ההגה..."/><button className="gold" onClick={()=>window.hayad.saveDraft(draft)}>שמור</button></section></div></div>}</>}
export default App;
